language: node_js
node_js:
  - "4.1"
before_install:
  - npm install -g tsd
deploy:
  provider: npm
  email: npm@smart-coordination.com
  api_key:
    secure: Kq/fZmk49dPohKmXwu+eFjE0Mpv4wYGHLeFbvxZUc6s+2fluFn3FEryIQiXRle1aexWDMpUhEJ6YlcxFRWMBOWcQ7/8uu1ckcjtRLMDRQstzi3RIlYxTnIM50xW9/zqblGJXaiHqHIrVFShvml9DUOr+Yq8axoS3L/mcbvG6N7/2OHbfpXHRhWbEF/ftlBbkEIEhk/Dic1riDXKIQr4AUZH38d6E5KWG9XCnCo9ilCNHdKLAkx7yhcoO5WJlVb2TWcb9Gkip4FH05nKyuX6jWKUWVFt/9jOunDcYgWXnnXJ+k7F+7uujCbJmVbFOfZKsvk0gCAbsjz4mG9yFHrD4d3nAu0xK8otrJRcpw/Er/HSRSq02fOowF9iYSTISzuLIa6OxE+8XPstJYUVWuxOqgf+Qpu2A68nlQz02xoHTIJB7jGnRDTyvxqJFa3ORpvJTjtplb2BolNMoSrE70uUnfgrh+QOFCcOdc7IEKwkeIRSLx1AQqQLJETzDOpiQV5qxdEF5a0K2QFi3qFk5wRIE1oNM+T4DF6vjkliV4q/E8ZdM4WvJ0MbztqE0laJYnuINi2NGRAoULHaa+dAtByd2F2x8b6CU1XmS+tLK9XdwbdUuPZCJmx6+RLmZFcVu7lTqFRLJeX60UYshdonkHEhGLaWeuHJm7nUIYz6tzRAh2pU=
  on:
    tags: true
    repo: pushrocks/smartparam
notifications:
  slack:
    secure: f5Uss0z9RPl/QcA/DroB8loyE93aOYI6bqCkrsiUscmZtlv/TVQtT4dxqGA6uvcG6iTQDBi3Ul88dQxWkRm4IqbhY35/iMaV2dHW4FVYMAh8GQMbsfL2sALCcufxD9blw47awv3iFcwhV1EeyesscjgL0JIjduk96v/7G/6QIO2838M1lzlgtj+kRUkim8qkaEs1je3gRrhMUIjLuAdscMXyUKYFMjWo9ACSjVUl30R/ZNemb18itIja6i92GotreBgcfEMczvy58ovDC7xdJUsY8LjMI01DwY+WPRnI0tAhsuI8moBwwcdM4e3bAjKjucQRjO33O5bMWRZ6QCiYd0DnCEFyCPQLJ4GSy/tkD00n8ijLHAOSV3AH1zNbdK1EAdSPQXDvlI36KJn/2hyQLoitGHVUPr76ujJWP82ypO2tgIp3XQU0dJVCxDuHnwJO2+hjdI+gCPqxNTpjeujHx3UdkTGNRjuuf9dlZ/D08fApjYxy2fxItTqo3QjP/nrqvBXUOPP8yPHpjIT4H2t5Pr4SJjBGI6X4qhKyFj6s9rA/Xu1rL+45zu1C3uC3z+u3T9UwrbzJ/cZM6r6UQvQmUvIfBNaMlg4I/diQCDIPL+Rhop2nylY3IcHmJnk2itn7kOqj1tohCpFEml5pRuSZy4udWywkdtyBAsHWFLF7oiQ=
